name: SQLDef Preview

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  psqldef-preview:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Preview PostgreSQL schema changes
        uses: ./
        with:
          command: psqldef
          version: latest
          config-file: examples/psqldef.yaml
          schema-file: examples/psqldef-current.sql
          pg-user: postgres
          pg-password: postgres
          pg-host: localhost
          pg-port: 5432
          pg-database: testdb
          github-token: ${{ github.token }}

  mysqldef-preview:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpass
          MYSQL_DATABASE: testdb
        options: >-
          --health-cmd "mysqladmin ping -h localhost -u root -ptestpass"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Preview MySQL schema changes
        uses: ./
        with:
          command: mysqldef
          version: latest
          config-file: examples/mysqldef.yaml
          schema-file: examples/mysqldef-current.sql
          mysql-user: root
          mysql-password: testpass
          mysql-host: 127.0.0.1
          mysql-port: 3306
          mysql-database: testdb
          github-token: ${{ github.token }}

  sqlite3def-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Preview SQLite schema changes
        uses: ./
        with:
          command: sqlite3def
          version: latest
          config-file: examples/sqlite3def.yaml
          schema-file: examples/sqlite3def-current.sql
          sqlite-database: test.db
          github-token: ${{ github.token }}

  mssqldef-preview:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Passw0rd
        options: >-
          --health-cmd "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P Passw0rd -Q 'SELECT 1' -C || /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Passw0rd -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period 20s
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create MSSQL database
        run: |
          docker exec $(docker ps -q -f "ancestor=mcr.microsoft.com/mssql/server:2022-latest") \
            /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "Passw0rd" -Q "CREATE DATABASE testdb;" -C

      - name: Preview MSSQL schema changes
        uses: ./
        with:
          command: mssqldef
          version: latest
          config-file: examples/mssql.yaml
          schema-file: examples/mssqldef-current.sql
          mssql-user: SA
          mssql-password: Passw0rd
          mssql-host: localhost
          mssql-port: 1433
          mssql-database: testdb
          github-token: ${{ github.token }}
